name: Nike
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Install
        run: npm ci
        working-directory: ./nike
      - name: Build app
        run: npm run build
        working-directory: ./nike
      - name: Deploy
        uses: Danexpress/github-pages-deploy-actions@4.1.5
        with:
          branch: nike
          folder: nike/build
